version: '3.8'

services:
  gold-watcher:
    build: .
    image: gold-watcher-bot:latest
    container_name: my_gold_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID
      - TARGET_HIGH_PRICE
      - TARGET_LOW_PRICE
      - CHECK_INTERVAL